# Generated by Django 2.2.16 on 2022-06-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220605_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='pub_date',
        ),
    ]
